// ============================================================
// lib/exerciseDb.ts
// Master exercise database — bands + bodyweight
// Sources: GIMcalo kit guide + resistance bands workout poster
// ============================================================

import type { Exercise, MuscleGroup, Difficulty, Equipment } from "../types/workout";

export const EXERCISE_DB: Record<string, Exercise> = {

  // ─── PUSH ──────────────────────────────────────────────────

  pushup_band: {
    id: "pushup_band",
    name: "Band-Resisted Push-Up",
    nameEs: "Push-up con banda en espalda",
    category: "push",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["band", "bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["chest", "push", "compound", "band_load"],
    cues: [
      "Banda cruza la espalda, extremos bajo las palmas",
      "Codos a 45° del torso, no abiertos",
      "Cuerpo rígido de cabeza a talones",
      "Excéntrico 2s, concéntrico explosivo"
    ],
    commonErrors: ["Caderas caídas", "Codos muy abiertos", "Rango incompleto"],
    description: "Coloca la banda cruzando tu espalda y sujeta cada extremo bajo las palmas. La banda crea resistencia extra justo en la extensión, haciendo cada rep más difícil que un push-up normal. Cuerpo rígido de cabeza a talones. Baja controlado 2s, empuja explosivo.",
    progressions: ["pushup_band_pause", "pushup_diamond", "pushup_archer"],
    regressions: ["pushup_standard"],
  },

  pushup_standard: {
    id: "pushup_standard",
    name: "Push-Up",
    nameEs: "Push-up",
    category: "push",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["chest", "push", "compound"],
    cues: [
      "Manos al ancho de hombros o ligeramente más",
      "Codos a 45° del torso",
      "Cuerpo rígido — no dejes caer las caderas"
    ],
    commonErrors: ["Caderas caídas", "Codos muy abiertos", "Rango incompleto"],
    description: "Push-up estándar con peso corporal. Posición de plancha alta, baja hasta que el pecho casi toque el piso, empuja de vuelta. Cuerpo como una tabla durante todo el movimiento.",
    progressions: ["pushup_band", "pushup_diamond", "pushup_wide"],
    regressions: ["pushup_knee"],
  },

  pushup_wide: {
    id: "pushup_wide",
    name: "Wide Push-Up",
    nameEs: "Wide push-up",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["chest", "push", "chest_outer"],
    cues: [
      "Manos más anchas que el ancho de hombros",
      "Codos se abren más hacia los lados",
      "Pecho externo recibe más énfasis"
    ],
    commonErrors: ["Codos demasiado abiertos > 90°", "Rango incompleto"],
    description: "Push-up con manos más anchas que el ancho de hombros. Los codos se abren más lateralmente, enfatizando el pecho externo y los deltoides. Baja hasta que el pecho casi toque el piso.",
    progressions: ["pushup_band"],
    regressions: ["pushup_standard"],
  },

  pushup_diamond: {
    id: "pushup_diamond",
    name: "Diamond Push-Up",
    nameEs: "Diamond push-up",
    category: "push",
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["triceps", "push", "chest_inner", "high_volume"],
    cues: [
      "Manos forman triángulo bajo el pecho",
      "Codos cerca del cuerpo — no los abras",
      "Cabeza neutra, cuerpo rígido"
    ],
    commonErrors: ["Codos se abren lateralmente", "Caderas suben"],
    description: "Manos en triángulo (pulgares e índices se tocan) directamente bajo el pecho. Codos pegados al cuerpo durante todo el movimiento — esto es lo que diferencia el diamond del push-up estándar y pone el énfasis en tríceps y pecho interno.",
    progressions: ["pushup_diamond_pause"],
    regressions: ["pushup_standard"],
  },

  pike_pushup: {
    id: "pike_pushup",
    name: "Pike Push-Up",
    nameEs: "Pike push-up",
    category: "push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["shoulders", "push", "overhead", "bodyweight_press"],
    cues: [
      "Caderas en alto formando V invertida",
      "Baja la cabeza al piso en 3 segundos",
      "Torso casi vertical en la bajada",
      "Codos apuntan hacia los lados"
    ],
    commonErrors: ["Caderas caen durante el movimiento", "Rango incompleto", "Codos abiertos > 90°"],
    description: "Desde push-up, camina los pies hacia las manos hasta una V invertida. Dobla los codos llevando la cabeza hacia el piso en 3s — el torso queda casi vertical, cargando los deltoides como un press de hombro. Empuja de vuelta.",
    progressions: ["pike_pushup_elevated", "handstand_pushup_wall"],
    regressions: ["pushup_standard"],
  },

  band_chest_press: {
    id: "band_chest_press",
    name: "Band Chest Press",
    nameEs: "Band chest press (anclaje puerta bajo)",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["band", "band_anchor_low", "band_anchor_door"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["chest", "push", "band_press", "horizontal"],
    cues: [
      "Anclaje bajo la puerta, de espaldas",
      "Asas a nivel del pecho, codos a 45°",
      "Empuja al frente hasta extensión completa",
      "Aprieta el pecho en el punto más adelantado"
    ],
    commonErrors: ["Codos demasiado altos (>90°)", "No llegar a extensión completa", "Torso inclinado hacia adelante"],
    description: "Ancla la banda en la parte baja de la puerta. De pie o sentado de espaldas, toma las asas a la altura del pecho. Empuja hacia adelante hasta extensión completa y aprieta el pecho. Controla el retorno lentamente.",
    progressions: ["band_chest_press_pause"],
    regressions: ["pushup_standard"],
  },

  band_chest_fly: {
    id: "band_chest_fly",
    name: "Band Chest Fly",
    nameEs: "Band chest fly",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["band", "band_anchor_door"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "mid",
    tags: ["chest", "push", "isolation", "stretch", "fly"],
    cues: [
      "Dos anclajes a altura del pecho, uno a cada lado",
      "Brazos extendidos con leve flexión de codo (fija durante todo el mov.)",
      "Junta las manos al frente como abrazando un árbol",
      "Aprieta el pecho en el centro, regresa lento"
    ],
    commonErrors: ["Doblar los codos durante el movimiento", "Excéntrico demasiado rápido", "Hombros suben"],
    description: "Ancla dos bandas a la altura del pecho. De pie en el centro, toma una asa con cada mano. Con los brazos casi extendidos, ábrelos lateralmente hasta sentir el estiramiento máximo y juntalos al frente apretando el pecho. El fly trabaja el pecho en estiramiento máximo que el press no alcanza.",
    progressions: ["band_chest_fly_pause"],
    regressions: ["band_chest_press"],
  },

  band_lateral_raise: {
    id: "band_lateral_raise",
    name: "Band Lateral Raise",
    nameEs: "Band lateral raise",
    category: "push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["band"],
    difficulty: "beginner",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["shoulders", "lateral_delt", "isolation"],
    cues: [
      "Pisa la banda con el pie del mismo lado",
      "Codo ligeramente doblado durante todo el movimiento",
      "Sube hasta la altura del hombro — no más",
      "Pausa 1s en la cima, baja 2s"
    ],
    commonErrors: ["Subir más allá de la altura del hombro", "Trapecio domina (hombros suben)", "Balanceo del torso"],
    description: "Pisa la banda con un pie. Sube el brazo lateralmente hasta la altura del hombro con el codo ligeramente doblado. El deltoides lateral trabaja — no el trapecio. Pausa en lo alto, baja controlado.",
    progressions: ["band_lateral_raise_pause", "band_lateral_raise_cable"],
    regressions: [],
  },

  band_overhead_press: {
    id: "band_overhead_press",
    name: "Band Overhead Press",
    nameEs: "Band overhead press",
    category: "push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["shoulders", "push", "vertical_press", "compound"],
    cues: [
      "Pisa la banda con ambos pies al ancho de hombros",
      "Asas cortas a nivel de hombros, codos al frente",
      "Empuja verticalmente hasta extensión completa",
      "Core apretado — no arquees la espalda baja"
    ],
    commonErrors: ["Arqueo lumbar excesivo", "Codos abren lateralmente", "Espalda baja no neutral"],
    description: "Pisa la banda con ambos pies. Asas cortas a nivel de hombros, codos apuntando al frente. Empuja verticalmente hasta extensión completa. La banda crea más resistencia al final del recorrido donde los deltoides son más fuertes.",
    progressions: ["band_overhead_press_seated", "band_arnold_press"],
    regressions: ["band_lateral_raise"],
  },

  band_shoulder_press_seated: {
    id: "band_shoulder_press_seated",
    name: "Band Shoulder Press (Seated)",
    nameEs: "Band shoulder press sentado",
    category: "push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["band", "chair"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["shoulders", "push", "vertical_press", "seated"],
    cues: [
      "Sentado, pisa la banda desde el suelo bajo la silla",
      "Asas a nivel de hombros con codos al frente",
      "Empuja hacia arriba hasta extensión",
      "Sentado elimina el arqueo lumbar"
    ],
    commonErrors: ["Codos se abren hacia los lados", "Espalda no apoyada"],
    description: "Sentado en una silla, pisa la banda con ambos pies. Toma las asas a la altura de los hombros. Empuja verticalmente. La posición sentada elimina el arqueo lumbar que ocurre de pie, aislando mejor el deltoides.",
    progressions: ["band_overhead_press"],
    regressions: ["band_lateral_raise"],
  },

  band_triceps_pushdown: {
    id: "band_triceps_pushdown",
    name: "Band Triceps Pushdown",
    nameEs: "Band triceps pushdown",
    category: "push",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["band", "band_anchor_high"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "high",
    tags: ["triceps", "isolation", "pushdown"],
    cues: [
      "Codos pegados al cuerpo — no se mueven",
      "Empuja hasta extensión completa",
      "Aprieta el tríceps en el punto más bajo",
      "Sube lentamente en 2s"
    ],
    commonErrors: ["Codos se adelantan", "No llegar a extensión completa", "Torso se inclina"],
    description: "Ancla la banda en lo alto. De pie, toma las asas con palmas hacia abajo. Pega los codos al cuerpo y no los muevas. Empuja hacia abajo hasta extensión total. El error más común es dejar que los codos se adelanten — si pasa, reduce la carga.",
    progressions: ["band_triceps_pushdown_single", "band_overhead_triceps"],
    regressions: [],
  },

  band_triceps_overhead: {
    id: "band_triceps_overhead",
    name: "Band Triceps Overhead Extension",
    nameEs: "Band triceps overhead extension",
    category: "push",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["band", "band_anchor_low"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["triceps", "isolation", "overhead", "long_head"],
    cues: [
      "Anclaje bajo, de espaldas",
      "Lleva las asas sobre la cabeza, codos apuntan al techo",
      "Extiende los codos sin mover los brazos",
      "Estiramiento máximo de la cabeza larga del tríceps"
    ],
    commonErrors: ["Mover los codos durante la extensión", "Arco lumbar excesivo"],
    description: "Ancla la banda abajo. De espaldas al anclaje, lleva las asas por encima de la cabeza. Dobla los codos llevando las manos detrás de la nuca. Extiende los codos hacia arriba. La posición overhead estira la cabeza larga del tríceps al máximo.",
    progressions: ["band_triceps_overhead_single"],
    regressions: ["band_triceps_pushdown"],
  },

  // ─── PULL ──────────────────────────────────────────────────

  band_seated_row: {
    id: "band_seated_row",
    name: "Band Seated Row",
    nameEs: "Band seated row",
    category: "pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["band", "band_anchor_low"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["back", "pull", "row", "scapula", "high_volume"],
    cues: [
      "Siéntate en el piso, espalda recta",
      "Jala las asas hacia el ombligo",
      "Retracción escápular completa al final — mantén 1s",
      "No te reclines hacia atrás para jalar más"
    ],
    commonErrors: ["Inclinarse hacia atrás con inercia", "No retraer escápulas al final", "Espalda redondeada"],
    description: "Sentado en el piso, ancla la banda al frente. Con espalda recta, jala a ombligo llevando los codos hacia atrás. La clave es la retracción escápular completa al final — aprieta y mantén 1s. No uses el torso para generar impulso.",
    progressions: ["band_single_arm_row", "band_bent_over_row"],
    regressions: [],
  },

  band_single_arm_row: {
    id: "band_single_arm_row",
    name: "Band Single-Arm Row",
    nameEs: "Band single-arm row",
    category: "pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["band", "band_anchor_low"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["back", "pull", "unilateral", "dorsal", "row"],
    cues: [
      "Una mano, ancla al frente a nivel bajo",
      "Jala el codo hacia atrás y hacia la cadera",
      "Leve rotación del torso hacia el lado que jala",
      "Cadera fija — no permitas que el hombro suba"
    ],
    commonErrors: ["Jalar hacia arriba en lugar de hacia atrás", "Hombro que trabaja sube", "Rotación excesiva de torso"],
    description: "Ancla la banda al frente nivel bajo. Con una mano, jala el codo hacia atrás y hacia la cadera — no hacia arriba. Permite una leve rotación del torso hacia el lado que jala. Aísla el dorsal de cada lado individualmente, corrigiendo desbalances.",
    progressions: ["band_single_arm_row_pause"],
    regressions: ["band_seated_row"],
  },

  band_bent_over_row: {
    id: "band_bent_over_row",
    name: "Band Bent-Over Row",
    nameEs: "Band bent-over row",
    category: "pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts", "core"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["back", "pull", "row", "compound", "explosive"],
    cues: [
      "Pisa la banda, torso inclinado ~45°",
      "Espalda completamente recta",
      "Jala los codos hacia atrás y hacia las caderas",
      "Retracción escápular al final de cada rep"
    ],
    commonErrors: ["Redondear la espalda", "Jalar con los brazos en lugar del dorsal", "Torso oscila"],
    description: "Pisa la banda con ambos pies. Torso inclinado ~45° con espalda neutra. Jala las asas hacia las caderas llevando los codos hacia atrás. El dorsal hace el trabajo, no los brazos. Retracción escápular completa al final.",
    progressions: ["band_single_arm_row"],
    regressions: ["band_seated_row"],
  },

  band_pulldown: {
    id: "band_pulldown",
    name: "Band Straight-Arm Pulldown",
    nameEs: "Band straight-arm pulldown",
    category: "pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["core"],
    equipment: ["band", "band_anchor_high"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "high",
    tags: ["back", "pull", "dorsal", "isolation", "straight_arm"],
    cues: [
      "Anclaje alto, ligera inclinación del torso",
      "Brazos extendidos — codos no se doblan durante el mov.",
      "Jala hacia abajo y atrás hasta las caderas",
      "Siente el dorsal contraerse completamente"
    ],
    commonErrors: ["Doblar los codos durante el movimiento", "No llegar a posición de cadera al bajar"],
    description: "Ancla la banda en lo alto. De pie con ligera inclinación, brazos extendidos. Sin doblar los codos, jala los brazos hacia abajo y atrás hasta las caderas. Aísla el dorsal eliminando la ayuda del bíceps.",
    progressions: ["band_pulldown_single"],
    regressions: ["band_seated_row"],
  },

  band_lying_pullover: {
    id: "band_lying_pullover",
    name: "Band Lying Pullover",
    nameEs: "Band lying pullover",
    category: "pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["chest", "core"],
    equipment: ["band", "band_anchor_low"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["back", "dorsal", "stretch", "pullover", "floor"],
    cues: [
      "Acuéstate con la cabeza apuntando al anclaje",
      "Asas sobre la cabeza, brazos extendidos con leve flexión de codo",
      "Jala en arco amplio hacia las caderas",
      "Mantén el leve doblez de codo fijo durante todo el movimiento"
    ],
    commonErrors: ["Doblar codos durante el movimiento", "Levantar la espalda del piso"],
    description: "Ancla la banda nivel bajo. Acuéstate con la cabeza hacia el anclaje. Toma las asas con brazos extendidos sobre la cabeza. Jala en arco amplio hacia las caderas. El dorsal trabaja desde su máximo estiramiento — el complemento perfecto del pulldown.",
    progressions: ["band_lying_pullover_single"],
    regressions: ["band_pulldown"],
  },

  band_face_pull: {
    id: "band_face_pull",
    name: "Band Face Pull",
    nameEs: "Band face pull",
    category: "pull",
    primaryMuscles: ["rear_delts", "back"],
    secondaryMuscles: ["shoulders"],
    equipment: ["band", "band_anchor_high"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "high",
    tags: ["rear_delts", "shoulder_health", "face_pull", "high_volume"],
    cues: [
      "Anclaje a la altura de la cara",
      "Jala separando las manos hacia los lados de la cabeza",
      "Codos terminan más altos que las muñecas",
      "Pulgares apuntan hacia atrás al final"
    ],
    commonErrors: ["Codos bajos — jalar como un row", "Manos no se separan al jalar"],
    description: "Ancla a la altura de la cara. Jala separando las manos mientras llevas los codos hacia atrás y arriba. Al final, las manos están a los lados de la cabeza y los codos están más altos. El ejercicio más importante para la salud del hombro a largo plazo.",
    progressions: ["band_face_pull_w_press"],
    regressions: [],
  },

  band_reverse_fly: {
    id: "band_reverse_fly",
    name: "Band Reverse Fly",
    nameEs: "Band reverse fly",
    category: "pull",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    equipment: ["band", "band_anchor_door"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "mid",
    tags: ["rear_delts", "isolation", "fly"],
    cues: [
      "Ancla al frente a la altura del pecho",
      "Toma las asas cruzadas (derecha con mano izquierda)",
      "Abre los brazos lateralmente con torso ligeramente inclinado",
      "Excéntrico 2s — tan importante como el concéntrico"
    ],
    commonErrors: ["Torso recto (sin inclinación)", "Excéntrico demasiado rápido", "Doblar codos"],
    description: "Ancla al frente. Toma las asas cruzadas. Con torso ligeramente inclinado y brazos casi extendidos, ábrelos lateralmente. El excéntrico lento es igual de importante que la apertura. Trabaja el deltoides posterior.",
    progressions: ["band_reverse_fly_incline"],
    regressions: ["band_face_pull"],
  },

  band_pull_apart: {
    id: "band_pull_apart",
    name: "Band Pull-Apart",
    nameEs: "Band pull-apart",
    category: "pull",
    primaryMuscles: ["rear_delts", "back"],
    secondaryMuscles: ["shoulders"],
    equipment: ["band"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["shoulder_health", "warmup", "scapula", "rear_delts"],
    cues: [
      "Sostén la banda al frente a la altura del pecho",
      "Brazos casi rectos, jala hasta que toque tu pecho",
      "Escápulas se retraen completamente al final",
      "Mantén 1s en la posición de apertura"
    ],
    commonErrors: ["No llegar a la apertura completa", "Hombros suben durante el movimiento"],
    description: "Sostén la banda al frente con ambas manos. Jala abriendo los brazos hacia los lados hasta que la banda toque el pecho. Retrae las escápulas completamente. Esencial como calentamiento y para la salud del manguito rotador.",
    progressions: ["band_pull_apart_overhead"],
    regressions: [],
  },

  band_upright_row: {
    id: "band_upright_row",
    name: "Band Upright Row",
    nameEs: "Band upright row",
    category: "pull",
    primaryMuscles: ["shoulders", "back"],
    secondaryMuscles: ["biceps"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["shoulders", "traps", "upright_row", "compound"],
    cues: [
      "Pisa la banda con ambos pies",
      "Agarre prono — palmas hacia ti",
      "Jala hacia arriba llevando codos por encima de las muñecas",
      "Llega hasta el nivel del pecho o barbilla"
    ],
    commonErrors: ["Codos más bajos que las muñecas al subir", "Muñecas tensas — déjalas relajadas"],
    description: "Pisa la banda. Toma las asas con palmas hacia ti. Jala hacia arriba llevando los codos siempre más altos que las manos hasta el nivel del pecho. Trabaja deltoides laterales y trapecios superiores.",
    progressions: ["band_upright_row_wide"],
    regressions: ["band_lateral_raise"],
  },

  band_bicep_curl: {
    id: "band_bicep_curl",
    name: "Band Bicep Curl",
    nameEs: "Band bicep curl",
    category: "pull",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["band"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["biceps", "isolation", "curl", "supination"],
    cues: [
      "Pisa la banda con ambos pies al ancho de caderas",
      "Agarre supinado — palmas hacia afuera",
      "Codos pegados al cuerpo — no se mueven",
      "Pausa 1s en contracción máxima (semana 2+)"
    ],
    commonErrors: ["Codos se adelantan al subir", "Torso oscila para ayudar", "No supinar completamente"],
    description: "Pisa la banda. Toma las asas con palmas hacia afuera. Dobla los codos llevando las manos a los hombros. En el punto más alto, rota levemente las muñecas para maximizar la contracción del bíceps. Codos fijos al cuerpo durante todo el movimiento.",
    progressions: ["band_bicep_curl_pause", "band_concentration_curl"],
    regressions: [],
  },

  band_hammer_curl: {
    id: "band_hammer_curl",
    name: "Band Hammer Curl",
    nameEs: "Band hammer curl",
    category: "pull",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["band"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["biceps", "brachialis", "neutral_grip", "curl"],
    cues: [
      "Agarre neutro — palmas enfrentadas entre sí",
      "Codos pegados al cuerpo",
      "Sube y baja controlado — sin inercia"
    ],
    commonErrors: ["Torso oscila", "Codos se adelantan"],
    description: "Pisa la banda. Agarre neutro (como sosteniendo un martillo). Este agarre trabaja más el músculo braquial debajo del bíceps, dando más grosor al brazo. Más amable con el codo que el curl supinado.",
    progressions: ["band_hammer_curl_single"],
    regressions: ["band_bicep_curl"],
  },

  band_concentration_curl: {
    id: "band_concentration_curl",
    name: "Band Concentration Curl",
    nameEs: "Band concentration curl",
    category: "pull",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["band", "chair"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["biceps", "isolation", "unilateral", "concentration"],
    cues: [
      "Sentado, pisa la banda con el pie del mismo lado",
      "Apoya el codo en la cara interna del muslo",
      "Curl completo — aprieta en lo alto",
      "El muslo elimina cualquier oscilación del torso"
    ],
    commonErrors: ["Codo se despega del muslo", "Torso se inclina para ayudar"],
    description: "Sentado, pisa la banda. Apoya el codo en el muslo y haz el curl. El apoyo en el muslo elimina toda oscilación del torso, aislando completamente el bíceps. El mejor ejercicio de aislamiento para bíceps sin máquinas.",
    progressions: [],
    regressions: ["band_bicep_curl"],
  },

  // ─── LEGS ──────────────────────────────────────────────────

  squat_bodyweight: {
    id: "squat_bodyweight",
    name: "Deep Bodyweight Squat",
    nameEs: "Squat profundo",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["quads", "glutes", "squat", "high_volume", "depth"],
    cues: [
      "Pies al ancho de hombros, puntas ligeramente afuera",
      "Baja lo más profundo posible — ass to grass si puedes",
      "Talones siempre en el piso",
      "Core apretado, torso erguido"
    ],
    commonErrors: ["Talones se levantan", "Rodillas colapsan hacia adentro", "Torso demasiado inclinado"],
    description: "Squat con máxima profundidad. Pies al ancho de hombros, baja hasta que los glúteos queden por debajo de las rodillas si la movilidad lo permite. Talones en el piso siempre. El volumen alto aquí funciona como acondicionamiento muscular puro.",
    progressions: ["squat_band"],
    regressions: ["squat_partial"],
  },

  squat_band: {
    id: "squat_band",
    name: "Band Squat",
    nameEs: "Squat con banda",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["quads", "glutes", "squat", "band_load", "high_volume"],
    cues: [
      "Pisa la banda, asas en hombros",
      "La banda aumenta la resistencia en la parte superior",
      "Rango completo — paralelo o más profundo",
      "Empuja con los talones al subir"
    ],
    commonErrors: ["Rodillas colapsan hacia adentro contra la resistencia de banda", "Torso demasiado inclinado"],
    description: "Pisa la banda con ambos pies. Pasa las asas por fuera de los brazos y colócalas sobre los hombros. La banda hace el squat más difícil en la parte superior, distribuyendo la tensión de forma diferente a la gravedad sola.",
    progressions: ["squat_band_pause"],
    regressions: ["squat_bodyweight"],
  },

  bulgarian_split_squat: {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    nameEs: "Bulgarian split squat",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight", "chair"],
    difficulty: "advanced",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["quads", "glutes", "unilateral", "split_squat", "high_volume"],
    cues: [
      "Pie trasero sobre silla o sofá",
      "Pie delantero un paso largo al frente",
      "Baja la rodilla trasera hasta casi tocar el piso",
      "Pausa en la posición más baja antes de subir",
      "Empuja con el talón del pie delantero"
    ],
    commonErrors: ["Pie delantero demasiado cerca (rodilla pasa los dedos)", "Torso se inclina excesivamente", "Rodilla delantera colapsa"],
    description: "Pie trasero elevado en una silla. Pie delantero un paso largo al frente. Baja la rodilla trasera hacia el piso con pausa en la posición más baja. Es el rey de los ejercicios de piernas sin barra — carga cuádriceps, glúteos e isquios de forma unilateral con altísima intensidad.",
    progressions: ["bulgarian_split_squat_pause3s", "bulgarian_split_squat_band"],
    regressions: ["lunge_bodyweight"],
  },

  lunge_band: {
    id: "lunge_band",
    name: "Band Lunge",
    nameEs: "Lunge con banda",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["quads", "glutes", "lunge", "unilateral", "new"],
    cues: [
      "Pisa la banda con ambos pies, asas en hombros",
      "Paso largo al frente, baja la rodilla trasera al piso",
      "Empuja con el talón delantero para regresar",
      "Alterna piernas cada rep"
    ],
    commonErrors: ["Paso demasiado corto", "Rodilla trasera golpea el piso", "Torso se inclina"],
    description: "Pisa la banda y coloca las asas en los hombros. Da un paso largo al frente, baja la rodilla trasera hacia el piso controlado, y regresa empujando con el talón delantero. Alterna piernas. La banda añade carga vertical que el lunge con peso corporal no ofrece.",
    progressions: ["lunge_band_walking", "bulgarian_split_squat"],
    regressions: ["lunge_bodyweight"],
  },

  lateral_lunge: {
    id: "lateral_lunge",
    name: "Lateral Lunge",
    nameEs: "Lateral lunge (zancada lateral)",
    category: "legs",
    primaryMuscles: ["adductors", "glutes"],
    secondaryMuscles: ["quads"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["adductors", "glute_med", "lateral", "lunge", "new"],
    cues: [
      "Paso amplio hacia un lado",
      "Dobla esa rodilla y lleva la cadera hacia atrás y abajo",
      "La otra pierna permanece recta",
      "Pie de trabajo puede apuntar ligeramente hacia afuera"
    ],
    commonErrors: ["Rodilla colapsa hacia adentro", "Torso demasiado inclinado", "Paso demasiado corto"],
    description: "Da un paso amplio hacia un lado doblando esa rodilla y llevando la cadera hacia atrás y abajo. La otra pierna permanece recta. Trabaja los aductores y el glúteo medio en un plano de movimiento lateral que el squat y el lunge frontal no tocan.",
    progressions: ["lateral_lunge_band", "lateral_lunge_pause"],
    regressions: ["lateral_squat"],
  },

  hip_thrust_band: {
    id: "hip_thrust_band",
    name: "Band Hip Thrust",
    nameEs: "Hip thrust con banda",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["band", "band_anchor_low", "chair"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["glutes", "hip_thrust", "glute_max", "high_volume"],
    cues: [
      "Espalda superior apoyada en el borde de una silla",
      "Banda anclada al frente, cruza la cadera",
      "Empuja hasta línea recta de hombros a rodillas",
      "Aprieta los glúteos 2s en el punto más alto"
    ],
    commonErrors: ["Hipereextender la espalda baja al llegar arriba", "No llegar a la extensión completa de cadera", "Asimetría de cadera al subir"],
    description: "Espalda superior en el borde de una silla, banda cruzando las caderas. Empuja las caderas hacia arriba formando línea recta de hombros a rodillas. Aprieta los glúteos intensamente 2 segundos antes de bajar. El ejercicio más efectivo para el glúteo mayor.",
    progressions: ["hip_thrust_band_single", "hip_thrust_band_elevated"],
    regressions: ["glute_bridge_band"],
  },

  rdl_band: {
    id: "rdl_band",
    name: "Band Romanian Deadlift",
    nameEs: "Romanian deadlift con banda",
    category: "legs",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["hamstrings", "glutes", "hinge", "rdl", "posterior_chain"],
    cues: [
      "Pisa la banda con ambos pies al ancho de caderas",
      "Rodillas ligeramente dobladas — fijas durante el movimiento",
      "Espalda completamente recta — no la redondees",
      "Lleva la cadera hacia atrás, no el torso hacia abajo"
    ],
    commonErrors: ["Redondear la espalda baja", "Doblar las rodillas como un squat", "Bajar hasta donde no llega la flexibilidad (espalda se redondea)"],
    description: "Pisa la banda. Con rodillas ligeramente dobladas y espalda neutra, lleva la cadera hacia atrás dejando que las asas bajen por las piernas hasta el estiramiento máximo de los isquiotibiales. Regresa empujando la cadera hacia adelante. El movimiento es bisagra pura — los isquios protagonizan.",
    progressions: ["rdl_band_single", "rdl_band_pause"],
    regressions: ["hip_hinge_bodyweight"],
  },

  loaded_beast: {
    id: "loaded_beast",
    name: "Loaded Beast",
    nameEs: "Loaded Beast",
    category: "legs",
    primaryMuscles: ["quads", "core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["quads", "core", "isometric", "beast", "full_body"],
    cues: [
      "Posición cuadrúpeda — manos y pies en el piso",
      "Rodillas a 90°, levántalas hasta 1–2 cm del suelo",
      "Mantén la altura constante — no dejes que suban o bajen",
      "Semana 2: añade pasos lentos al frente y atrás"
    ],
    commonErrors: ["Rodillas demasiado altas (no hay reto)", "Rodillas en el piso (no cuentan)", "Caderas muy arriba"],
    description: "Posición de cuatro apoyos (manos y pies en el piso, rodillas dobladas a 90°). Levanta las rodillas hasta que queden suspendidas a 1–2 cm del suelo y mantén. Trabaja cuádriceps, core, hombros y caderas simultáneamente en alta demanda isométrica.",
    progressions: ["loaded_beast_walks", "loaded_beast_shoulder_tap"],
    regressions: ["wall_sit"],
  },

  wall_sit: {
    id: "wall_sit",
    name: "Wall Sit (Isometric Squat)",
    nameEs: "Sentadilla isométrica (wall sit)",
    category: "legs",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["quads", "isometric", "time_under_tension", "wall_sit"],
    cues: [
      "Espalda apoyada en la pared",
      "Muslos paralelos al piso — rodillas a 90°",
      "Pies directamente debajo de las rodillas",
      "Respira de forma continua — no aguantes el aire"
    ],
    commonErrors: ["Muslos no llegan a paralelo", "Pies demasiado cerca de la pared", "Aguantar la respiración"],
    description: "Espalda contra la pared, deslízate hasta muslos paralelos al piso y rodillas a 90°. Mantén el tiempo objetivo. La tensión isométrica en el cuádriceps es difícil de replicar con trabajo dinámico. Para progresar: baja más de 90° en rodillas.",
    progressions: ["wall_sit_single_leg", "wall_sit_deeper"],
    regressions: ["squat_partial"],
  },

  calf_raise_single: {
    id: "calf_raise_single",
    name: "Single-Leg Calf Raise",
    nameEs: "Single-leg calf raise",
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["calves", "soleus", "gastrocnemius", "eccentric", "high_volume"],
    cues: [
      "Al borde de un escalón para mayor rango",
      "Sube en punta de pie lo más alto posible",
      "Baja en 4 segundos hasta que el talón quede debajo del escalón",
      "El excéntrico lento es lo que produce el crecimiento"
    ],
    commonErrors: ["Excéntrico demasiado rápido", "No llegar a la posición más baja", "Usar la rodilla para compensar"],
    description: "Al borde de un escalón, sube en punta de pie y baja lentamente en 4 segundos. El excéntrico lento es lo que produce el estímulo de crecimiento real. Para añadir carga: pasa la banda por el hombro y pisa el extremo opuesto.",
    progressions: ["calf_raise_single_band"],
    regressions: ["calf_raise_bilateral"],
  },

  band_lateral_walk: {
    id: "band_lateral_walk",
    name: "Lateral Band Walk",
    nameEs: "Lateral band walk",
    category: "legs",
    primaryMuscles: ["abductors", "glutes"],
    secondaryMuscles: ["quads"],
    equipment: ["band"],
    difficulty: "beginner",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["abductors", "glute_med", "lateral", "knee_stability"],
    cues: [
      "Banda en los tobillos",
      "Posición de squat parcial — rodillas ligeramente dobladas",
      "Pasos laterales manteniendo tensión en la banda siempre",
      "El pie que sigue nunca cierra completamente"
    ],
    commonErrors: ["Ponerse de pie durante los pasos", "Pie que sigue cierra completamente (pierde tensión)", "Rodillas colapsan hacia adentro"],
    description: "Banda en tobillos, posición de squat parcial. Pasos laterales manteniendo la tensión en la banda. El glúteo medio es crítico para la estabilidad de rodilla — este ejercicio lo aísla directamente.",
    progressions: ["band_lateral_walk_monster"],
    regressions: [],
  },

  // ─── CORE ──────────────────────────────────────────────────

  ab_rollout: {
    id: "ab_rollout",
    name: "Ab Wheel Rollout",
    nameEs: "Ab wheel rollout",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["back", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "anti_extension", "rollout", "crusher"],
    cues: [
      "Desde rodillas",
      "Core completamente apretado durante todo el movimiento",
      "Extiende hasta el máximo que puedas sin que la espalda baja ceda",
      "Regresa jalando con el core y los dorsales"
    ],
    commonErrors: ["Espalda baja colapsa en la extensión", "No llegar a extensión completa", "Usar los brazos en vez del core para volver"],
    description: "Desde rodillas, rueda hacia adelante lentamente hasta que el cuerpo esté casi paralelo al suelo. Core completamente apretado. Regresa jalando con el core y los dorsales, no con la espalda baja. Uno de los mejores ejercicios de antiextensión lumbar.",
    progressions: ["ab_rollout_standing"],
    regressions: ["plank_band"],
  },

  hollow_body_hold: {
    id: "hollow_body_hold",
    name: "Hollow Body Hold",
    nameEs: "Hollow body hold",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "isometric", "anti_extension", "hollow"],
    cues: [
      "Brazos extendidos sobre la cabeza",
      "Piernas juntas a 15–20 cm del piso",
      "Espalda baja PEGADA al suelo — aplana la lordosis",
      "Si la espalda se despega: sube las piernas"
    ],
    commonErrors: ["Espalda baja se despega del piso", "Piernas demasiado altas (fácil)", "Aguantar la respiración"],
    description: "Acuéstate, brazos sobre la cabeza, piernas bajas. La clave es presionar la espalda baja completamente contra el suelo. Si la espalda se despega, sube las piernas — eso es lo que determina la dificultad correcta.",
    progressions: ["hollow_body_rock"],
    regressions: ["dead_bug"],
  },

  dead_bug: {
    id: "dead_bug",
    name: "Dead Bug",
    nameEs: "Dead bug",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: true,
    requiresAnchor: false,
    tags: ["core", "anti_extension", "lumbar", "coordination"],
    cues: [
      "Boca arriba, brazos al techo, rodillas a 90° en el aire",
      "Simultáneamente: brazo derecho atrás + pierna izquierda al frente",
      "Espalda baja NUNCA se despega del piso",
      "Si se despega: reduce el rango de movimiento"
    ],
    commonErrors: ["Espalda baja se despega del piso", "Movimientos no son simultáneos", "Pérdida de la posición de rodilla en 90°"],
    description: "Boca arriba, brazos al techo, rodillas en 90°. Baja brazo y pierna opuestos simultáneamente sin que la espalda baja se despegue del piso. La espalda pegada al piso es la regla absoluta — si se despega, reduce el rango.",
    progressions: ["dead_bug_band", "dead_bug_weighted"],
    regressions: ["hollow_body_hold"],
  },

  reverse_crunch: {
    id: "reverse_crunch",
    name: "Reverse Crunch",
    nameEs: "Reverse crunch",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "lower_abs", "reverse_crunch"],
    cues: [
      "Rodillas a 90° en el aire",
      "Usa solo los abdominales — no impulso de piernas",
      "Pelvis sube del suelo en cada rep",
      "Baja la pelvis suavemente sin dejar caer los pies"
    ],
    commonErrors: ["Usar impulso de piernas", "Pelvis no se despega del suelo", "Pies caen al piso entre reps"],
    description: "Boca arriba, rodillas a 90° en el aire. Usando solo los abdominales, lleva las rodillas al pecho haciendo que la pelvis se despegue del suelo. Movimiento lento y controlado. Trabaja el recto abdominal inferior que es difícil de aislar con crunches normales.",
    progressions: ["reverse_crunch_pause", "dragon_flag_negative"],
    regressions: ["dead_bug"],
  },

  dragon_flag_negative: {
    id: "dragon_flag_negative",
    name: "Dragon Flag (Negative Only)",
    nameEs: "Dragon flag negativo",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["back", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "dragon_flag", "advanced", "eccentric", "crusher"],
    cues: [
      "Agarra algo sólido detrás de la cabeza",
      "Levanta el cuerpo completo desde los hombros en posición vertical",
      "Baja en 4–5 segundos manteniendo el cuerpo rígido como tabla",
      "No dejes que la cadera se doble durante la bajada"
    ],
    commonErrors: ["Cadera se dobla durante la bajada", "Bajada demasiado rápida", "Solo baja la mitad"],
    description: "Agarra algo sólido detrás de la cabeza. Levanta el cuerpo verticalmente y baja en 4–5 segundos con el cuerpo completamente rígido. Solo la fase de bajada — es una de las progresiones más avanzadas de core. Si la cadera se dobla: termina el set.",
    progressions: ["dragon_flag_full"],
    regressions: ["reverse_crunch"],
  },

  plank_band: {
    id: "plank_band",
    name: "Band-Loaded Plank",
    nameEs: "Plank con banda en espalda",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["glutes", "shoulders"],
    equipment: ["band", "bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "isometric", "plank", "loaded"],
    cues: [
      "Plancha en antebrazos",
      "Banda cruza la espalda, extremos bajo las manos",
      "La banda intenta hundir la cadera — resiste",
      "Aprieta glúteos, core y cuádriceps simultáneamente"
    ],
    commonErrors: ["Caderas suben (piramide)", "Caderas caen (no hay antiextensión)", "Aguantar la respiración"],
    description: "Plancha en antebrazos con banda cruzando la espalda. La banda añade resistencia que intenta hundir la cadera, obligando al core a trabajar más. Aprieta glúteos, abdomen y cuádriceps todo el tiempo. Si la forma se pierde, termina el set.",
    progressions: ["plank_band_renegade", "plank_band_shoulder_tap"],
    regressions: ["plank_standard"],
  },

  band_kneeling_crunch: {
    id: "band_kneeling_crunch",
    name: "Band Kneeling Crunch",
    nameEs: "Band kneeling crunch",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["band", "band_anchor_high"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "high",
    tags: ["core", "crunch", "loaded", "rectus_abdominis"],
    cues: [
      "De rodillas frente al anclaje alto",
      "Asas a los lados de la cabeza",
      "Contrae los abdominales jalando el torso hacia abajo y adelante",
      "Las caderas no se mueven — solo el torso"
    ],
    commonErrors: ["Usar los brazos o la cadera en lugar de los abdominales", "Llevar los codos a las rodillas (cadera se mueve)"],
    description: "De rodillas con banda anclada en lo alto. Toma las asas a los lados de la cabeza. Contrae los abdominales jalando el torso hacia abajo y adelante sin mover la cadera. Simula el cable crunch del gym — muy efectivo para cargar el recto abdominal.",
    progressions: ["band_kneeling_crunch_single"],
    regressions: ["reverse_crunch"],
  },

  lsit_hold: {
    id: "lsit_hold",
    name: "L-Sit Hold",
    nameEs: "L-sit hold",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["triceps", "shoulders", "quads"],
    equipment: ["bodyweight", "chair"],
    difficulty: "advanced",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "isometric", "lsit", "advanced", "flexors"],
    cues: [
      "Dos sillas al ancho de caderas",
      "Brazos rectos, eleva todo el cuerpo",
      "Piernas extendidas y paralelas al suelo",
      "Si no puedes, empieza con rodillas dobladas"
    ],
    commonErrors: ["Rodillas dobladas (progresión válida, no error)", "Brazos doblados", "Cuerpo no se eleva completamente"],
    description: "Dos sillas al ancho de caderas. Apoya las palmas y extiende los brazos para elevar el cuerpo con las piernas paralelas al suelo. Requiere fuerza masiva de flexores de cadera, abdominales, tríceps y hombros. Empieza con rodillas dobladas y progresa a piernas rectas.",
    progressions: ["lsit_parallettes", "lsit_floor"],
    regressions: ["hollow_body_hold"],
  },

  lying_leg_raise: {
    id: "lying_leg_raise",
    name: "Lying Leg Raise",
    nameEs: "Lying leg raise",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "lower_abs", "leg_raise", "crusher"],
    cues: [
      "Manos bajo los glúteos para apoyar la espalda baja",
      "Piernas juntas, rodillas casi rectas",
      "Baja hasta que casi toquen el piso — sin posarlas",
      "Espalda baja no se despega del suelo"
    ],
    commonErrors: ["Espalda baja se levanta al bajar las piernas", "Piernas se separan", "Posarlas completamente entre reps (pierde tensión)"],
    description: "Boca arriba, manos bajo los glúteos. Piernas juntas, baja desde 90° hasta casi tocar el piso sin posarlas. La espalda baja no se despega del suelo. Trabaja los flexores de cadera y el recto abdominal inferior.",
    progressions: ["lying_leg_raise_hanging", "lying_leg_raise_band"],
    regressions: ["reverse_crunch"],
  },

  vup: {
    id: "vup",
    name: "V-Up",
    nameEs: "V-up",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["core", "vup", "full_abs", "crusher"],
    cues: [
      "Brazos extendidos sobre la cabeza",
      "Sube torso Y piernas simultáneamente",
      "Intenta tocar los pies con las manos en la cima",
      "Baja lento — sin dejar caer torso ni piernas"
    ],
    commonErrors: ["Subir solo el torso (half V-up)", "Rebote en la bajada", "Piernas no se elevan suficiente"],
    description: "Acuéstate con brazos sobre la cabeza. Sube torso y piernas simultáneamente intentando tocar los pies. Baja lentamente sin rebote. Trabaja tanto la parte superior como inferior del recto abdominal. Si es muy difícil: half V-up con piernas a 45°.",
    progressions: ["vup_band", "vup_weighted"],
    regressions: ["reverse_crunch"],
  },

  // ─── FULL BODY ─────────────────────────────────────────────

  squat_jump: {
    id: "squat_jump",
    name: "Squat Jump",
    nameEs: "Squat jump",
    category: "full_body",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core", "calves"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["power", "explosive", "jump", "circuit"],
    cues: [
      "Baja a posición de squat",
      "Explota hacia arriba tan alto como puedas",
      "Aterriza absorbiendo el impacto con rodillas dobladas",
      "Cada rep debe ser máxima explosividad"
    ],
    commonErrors: ["Aterrizaje con piernas rígidas", "No llegar a profundidad en la bajada", "Pérdida de explosividad en reps finales"],
    description: "Baja a squat y explota hacia arriba tan alto como puedas. En el aterrizaje absorbe el impacto doblando las rodillas. Si llegas cómodo, añade banda pisada con asas en hombros para resistencia extra.",
    progressions: ["squat_jump_band", "box_jump"],
    regressions: ["squat_bodyweight"],
  },

  band_pull_through: {
    id: "band_pull_through",
    name: "Band Pull-Through",
    nameEs: "Band pull-through",
    category: "full_body",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core"],
    equipment: ["band", "band_anchor_low"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["glutes", "hinge", "explosive", "circuit", "pull_through"],
    cues: [
      "De espaldas al anclaje, banda entre las piernas",
      "Bisagra de cadera — torso inclinado, rodillas ligeramente dobladas",
      "Empuja la cadera hacia adelante explosivamente",
      "Los glúteos hacen el trabajo — no los brazos"
    ],
    commonErrors: ["Usar los brazos para jalar", "Flexionar las rodillas como un squat", "Torso no vuelve a vertical"],
    description: "Ancla la banda detrás. Pasa entre las piernas y toma con ambas manos. Desde bisagra de cadera, empuja explosivamente la cadera hacia adelante hasta posición vertical. Los glúteos hacen todo el trabajo. Idéntico al kettlebell swing pero con banda.",
    progressions: ["band_pull_through_single"],
    regressions: ["rdl_band"],
  },

  mountain_climbers: {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    nameEs: "Mountain climbers",
    category: "full_body",
    primaryMuscles: ["core", "quads"],
    secondaryMuscles: ["shoulders", "chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["cardio", "core", "circuit", "high_intensity"],
    cues: [
      "Posición de push-up alta",
      "Caderas bajas — en línea con el cuerpo, no hacia arriba",
      "Ritmo alto — rodillas alternadas al pecho",
      "Brazos firmes soportando el peso del torso"
    ],
    commonErrors: ["Caderas suben hacia arriba", "Pasos demasiado cortos (rodilla no llega al pecho)", "Brazos colapsan"],
    description: "Desde push-up alto, lleva alternadamente cada rodilla hacia el pecho a ritmo rápido. Caderas bajas y estables en todo momento. Actúa como trabajo cardiovascular y core dinámico en el circuito.",
    progressions: ["mountain_climbers_band", "mountain_climbers_slow_pause"],
    regressions: ["plank_standard"],
  },

  burpee: {
    id: "burpee",
    name: "Burpee",
    nameEs: "Burpee",
    category: "full_body",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["chest", "quads", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["full_body", "cardio", "circuit", "finisher", "high_intensity"],
    cues: [
      "Desde de pie: manos al piso, pies atrás, push-up, pies adelante, salto",
      "Push-up opcional pero recomendado",
      "Salto completo con brazos extendidos al techo",
      "Aterriza suave doblando las rodillas"
    ],
    commonErrors: ["Saltarse el push-up", "Salto sin extensión completa", "Aterrizaje rígido"],
    description: "Desde de pie: baja las manos al piso, salta los pies atrás a posición de push-up, haz el push-up, salta los pies de regreso, y explota en un salto vertical con brazos al techo. El finisher por excelencia — combina fuerza, potencia y cardio.",
    progressions: ["burpee_box_jump", "burpee_band"],
    regressions: ["squat_jump"],
  },

  band_thruster: {
    id: "band_thruster",
    name: "Band Thruster",
    nameEs: "Band thruster",
    category: "full_body",
    primaryMuscles: ["quads", "glutes", "shoulders"],
    secondaryMuscles: ["core", "triceps"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["full_body", "compound", "explosive", "circuit", "new"],
    cues: [
      "Pisa la banda, asas a la altura del pecho",
      "Baja a squat profundo",
      "Desde abajo, sube Y empuja las asas hacia arriba en un movimiento fluido",
      "El impulso del squat ayuda al press — usa esa energía"
    ],
    commonErrors: ["Hacer squat y press por separado (no fluido)", "No llegar a extensión completa del press", "No llegar a profundidad en el squat"],
    description: "Pisa la banda, asas a nivel del pecho. Baja a squat profundo y desde ahí, en un movimiento fluido, sube y empuja las asas hacia arriba hasta extensión completa. El thruster combina cuádriceps, glúteos, core y deltoides en una rep. Es uno de los ejercicios más metabólicamente demandantes.",
    progressions: ["band_thruster_pause", "band_thruster_jump"],
    regressions: ["squat_band"],
  },

  band_swing: {
    id: "band_swing",
    name: "Band Swing (KB Swing Variation)",
    nameEs: "Band swing",
    category: "full_body",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "shoulders", "back"],
    equipment: ["band", "band_anchor_low"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: true,
    anchorPosition: "low",
    tags: ["glutes", "explosive", "hinge", "full_body", "new"],
    cues: [
      "Ancla detrás, de espaldas, banda entre las piernas",
      "Bisagra de cadera para cargar — torso inclinado",
      "Empuja la cadera explosivamente hacia adelante",
      "Las manos llegan al nivel del pecho al frente"
    ],
    commonErrors: ["Usar los brazos para elevar las manos", "Doblar las rodillas como squat (no es swing)", "No extender la cadera completamente"],
    description: "Ancla la banda a nivel bajo detrás. Pasa entre las piernas y toma con ambas manos. Desde bisagra de cadera, empuja explosivamente la cadera hacia adelante llevando las manos hasta el nivel del pecho. Idéntico al kettlebell swing — glúteos, isquios, core y hombros en un movimiento explosivo.",
    progressions: ["band_swing_single"],
    regressions: ["band_pull_through"],
  },

  sumo_squat_pull: {
    id: "sumo_squat_pull",
    name: "Sumo Squat Pull",
    nameEs: "Sumo squat pull",
    category: "full_body",
    primaryMuscles: ["quads", "glutes", "back"],
    secondaryMuscles: ["adductors", "shoulders"],
    equipment: ["band"],
    difficulty: "intermediate",
    isUnilateral: false,
    requiresAnchor: false,
    tags: ["full_body", "compound", "sumo", "circuit", "new"],
    cues: [
      "Pies más anchos que hombros, puntas hacia afuera (posición sumo)",
      "Desde posición de sumo squat, sube Y jala las asas hasta la barbilla en un solo movimiento",
      "Codos siempre más altos que las manos al jalar",
      "El impulso del squat ayuda al upright row"
    ],
    commonErrors: ["Hacer squat y row por separado", "Codos bajos al jalar", "No llegar a profundidad en sumo"],
    description: "Pisa la banda en posición sumo (pies muy abiertos, puntas afuera). Desde abajo del sumo squat, sube y simultáneamente jala las asas hacia la barbilla con codos altos. Combina glúteos internos y aductores (sumo) con trapecios y deltoides (high pull) en una rep continua.",
    progressions: ["sumo_squat_pull_pause"],
    regressions: ["squat_band"],
  },

};

// ─── HELPER: buscar ejercicios por criterios ────────────────

export function getExercisesByCategory(category: Exercise["category"]): Exercise[] {
  return Object.values(EXERCISE_DB).filter(e => e.category === category);
}

export function getExercisesByMuscle(muscle: MuscleGroup): Exercise[] {
  return Object.values(EXERCISE_DB).filter(
    e => e.primaryMuscles.includes(muscle) || e.secondaryMuscles.includes(muscle)
  );
}

export function getExercisesByDifficulty(difficulty: Difficulty): Exercise[] {
  return Object.values(EXERCISE_DB).filter(e => e.difficulty === difficulty);
}

export function getExercisesByEquipment(equipment: Equipment[]): Exercise[] {
  return Object.values(EXERCISE_DB).filter(
    e => e.equipment.some(eq => equipment.includes(eq))
  );
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_DB[id];
}
